# Generated by Django 5.1.2 on 2024-10-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_verified_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
