# Generated by Django 5.1.2 on 2024-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
