# Generated by Django 5.1.2 on 2024-11-12 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organization_discord_organization_email_and_more"),
        ("users", "0007_user_imageurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("bookmark_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userId",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
