# Generated by Django 5.1.2 on 2024-11-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="bookmarked",
            field=models.BooleanField(default=False),
        ),
    ]
