# Generated by Django 5.1.2 on 2024-11-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_bookmark_bookmarked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="bookmarked",
        ),
    ]
