# Generated by Django 5.1.2 on 2024-10-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_ratings', '0001_initial'),
        ('users', '0007_user_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentRating',
            fields=[
                ('usercomment_id', models.AutoField(primary_key=True, serialize=False)),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments_rating', to='comments_and_ratings.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments_rating', to='users.user')),
            ],
        ),
    ]
