# Generated by Django 5.1.2 on 2024-10-30 22:52

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_ratings', '0002_usercommentrating'),
        ('organizations', '0007_organization_number_of_star_rating'),
        ('users', '0007_user_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2001, 9, 11, 8, 46)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(default='No Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(blank=True, default='No Title', max_length=100),
        ),
        migrations.CreateModel(
            name='UserOrgRating',
            fields=[
                ('userorg_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orgs_rating', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orgs_rating', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'org')},
            },
        ),
    ]
