# Generated by Django 5.1.2 on 2024-11-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_ratings', '0004_alter_usercommentrating_created_at'),
        ('users', '0007_user_imageurl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommentrating',
            unique_together={('user', 'comment')},
        ),
        migrations.DeleteModel(
            name='UserOrgRating',
        ),
    ]
