# Generated by Django 5.1.2 on 2024-11-13 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments_and_ratings",
            "0005_alter_usercommentrating_unique_together_and_more",
        ),
        ("organizations", "0008_organization_discord_organization_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercommentrating",
            name="org",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users.Bookmark.org+",
                to="organizations.organization",
            ),
        ),
    ]
