# Generated by Django 5.1.2 on 2024-11-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments_and_ratings", "0007_alter_usercommentrating_org"),
        ("organizations", "0008_organization_discord_organization_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommentrating",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users.Bookmark.org+",
                to="organizations.organization",
            ),
        ),
    ]
