# Generated by Django 5.1.2 on 2024-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organization_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="number_of_star_rating",
            field=models.IntegerField(default=0),
        ),
    ]
