# Generated by Django 5.1.2 on 2024-11-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organization_discord_organization_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
