tags = {
    "Academic": 1,
    "Advocacy": 2,
    "Arts": 3,
    "Automotive": 4,
    "Business": 5,
    "Charity": 6,
    "Community Service": 7,
    "Competitions": 8,
    "Construction": 9,
    "Culture": 10,
    "Dance": 11,
    "Debate": 12,
    "Engineering": 13,
    "Entrepreneurship": 14,
    "Environmental": 15,
    "Finance": 16,
    "Food": 17,
    "Gaming": 18,
    "Health": 19,
    "Innovation": 20,
    "International": 21,
    "Language": 22,
    "Leadership": 23,
    "LGBTQ+": 24,
    "Literature": 25,
    "Media": 26,
    "Mental Health": 27,
    "Music": 28,
    "Networking": 29,
    "Politics": 30,
    "Professional Development": 31,
    "Recreation": 32,
    "Religious": 33,
    "Robotics": 34,
    "Science": 35,
    "Social": 36,
    "Sports": 37,
    "Sustainability": 38,
    "Technology": 39,
    "Volunteering": 40,
    "Wellness": 41,
    "Women's Empowerment": 42,
    "Performing Arts": 43,
    "Film": 44,
    "Photography": 45,
    "Law": 46,
    "Mentorship": 47,
    "Fundraising": 48,
    "Comedy": 49,
    "Artificial Intelligence": 50
}
